version: '3.4'

services:
  inventory.supply.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:80"
      - "44301:443"
  inventory.stock.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:80"
      - "44302:443"
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
  users:
    ports:
      - "9000:9000"
  web:
    ports:
      - "3000:3000"
  mongodb:
    ports:
      - "27018:27017"
  mssql:
    ports:
      - "1433:1433"